### ISSUE TITLE
Server script compile error.

### ISSUE THREAD

**Issue by BTFighter** [JezuzLizard/T4ZM-Zombie-Bots#1]
![Untitled1](https://github.com/JezuzLizard/T4ZM-Zombie-Bots/assets/45516471/70199c16-04ea-45d3-890a-49b9aff0dd8e)

**Comment by ineedbots** [comment]
update to latest plutonium

**Comment by BTFighter** [comment]
Updated, different problem
![Untitled](https://github.com/JezuzLizard/T4ZM-Zombie-Bots/assets/45516471/9efac53a-e0d6-4299-b0e1-a2536d97292c)
.
