### ISSUE TITLE
Server script compile error updated version.

### ISSUE THREAD

**Issue by BTFighter** [JezuzLizard/T4ZM-Zombie-Bots#2]
![Untitled](https://github.com/JezuzLizard/T4ZM-Zombie-Bots/assets/45516471/317ec684-074f-4dd5-ad30-401fb7af92dc)

**Comment by JezuzLizard** [comment]
This mod requires this mod as a dependency https://github.com/JezuzLizard/T4ZM-Script-Overhaul

**Comment by BTFighter** [comment]
Works, massive thanks for the help and the mod!
![image](https://github.com/JezuzLizard/T4ZM-Zombie-Bots/assets/45516471/777ffc53-4d48-467f-bc76-561d5996b29b)
