### ISSUE TITLE
"Default Weapon"

### ISSUE THREAD

**Issue by BTFighter** [JezuzLizard/T4ZM-Zombie-Bots#6]
![image](https://github.com/JezuzLizard/T4ZM-Zombie-Bots/assets/45516471/efc0cdce-8175-4369-b27d-816ccfee90ea)

Buying any weapon on all but Nacht Der Untoten will give "Default Weapon" than the expected weapon.

**Comment by ineedbots** [comment]
set the `weapon_load_order` dvar to "ff" (or 2),

this is a basegame issue where weapon files will load from fastfile ONLY (if fs_game is blank) or ONLY iwd (when fs_game isn't blank)
